services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./app-state/user:/config/www/user
      - ./app-state/logs:/config/www/logs
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app-state/caddy/data:/data
      - ./app-state/caddy/config:/config
