# yaml-language-server: $schema=https://gist.githubusercontent.com/sargunv/c2ca41a08391cd06feaad97aece309e4/raw/empty-json-schema.json
title: Default
'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        options:
          type: tab
          title: Options
          fields:
            header.exclude_from_nav:
              type: checkbox
              label: Exclude from Navigation
              validate:
                type: bool
